public class CalClass {
    public static integer Addition(Integer A, Integer B){
        system.debug('I am inside Addition');
        return null;
        }
    public static integer Subtraction(Integer A, Integer B){
        system.debug('I am inside Subtraction');
        return null;
        }
	public static void ForDebug(Integer A, Integer B){
        system.debug('I am inside ForDebug');
       }
    public CalClass(){
        system.debug('I am inside constructor');
    }
    
}